repos:
  # 1. pre-commit-hooks: General-purpose hooks for checking file formats and naming conventions
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: name-tests-test
        args: ["--pytest-test-first"]

  # 2. detect-secrets: Scans for secrets in the codebase
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: package.lock.json

  # 3. ruff-pre-commit: Linting and formatting for Python code using ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
      - id: ruff-format
        types_or: [ python, pyi ]

  # 4. mirrors-mypy: Static type checking for Python code using mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - pytest==8.4.2
        args: ["--config-file=pyproject.toml"]
        language_version: python3.13

  # 5. bandit: Security analysis for Python code
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  # 6. gitlint: Linting for Git commit messages
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    -   id: gitlint
